# Generated by Django 2.2.6 on 2019-10-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
    ]
